{ config, pkgs, ... }:

let
  # Stow package holding the personal Hyprland overrides: the custom/ files that
  # end-4's config sources after its own defaults, plus shaders/ which upstream
  # does not ship at all. Upstream keeps updating freely underneath.
  dotfilesDir = "${config.home.homeDirectory}/.config/dotfiles";
  stowPackage = "hypr-local";

  # illogical-flake's copyIllogicalImpulseConfigs activation step does
  # `rm -rf ~/.config/hypr` and copies the flake's dotfiles input over it, so the
  # overrides have to be re-stowed after that step. custom/env.lua and
  # custom/general.lua are generated by that module and are deliberately NOT in
  # the stow package -- everything personal fits in the other custom/ files.
in
{
  home.activation.stowHyprLocal =
    config.lib.dag.entryAfter [ "copyIllogicalImpulseConfigs" ] ''
      packageDir="${dotfilesDir}/${stowPackage}"

      if [ ! -d "$packageDir" ]; then
        echo "hypr-local: $packageDir not found, skipping stow" >&2
      else
        # Clear the copies illogical-flake just laid down, otherwise stow reports
        # a conflict and refuses. Only paths the stow package actually owns are
        # touched; everything else upstream shipped is left alone.
        while IFS= read -r -d "" packageFile; do
          relativePath="''${packageFile#$packageDir/}"
          target="${config.home.homeDirectory}/$relativePath"
          if [ -e "$target" ] && [ ! -L "$target" ]; then
            $DRY_RUN_CMD rm -f "$target"
          fi
        done < <(find "$packageDir" -type f -print0)

        # --no-folding keeps hypr/custom a real directory so the module-generated
        # env.lua and general.lua can sit next to the stowed symlinks.
        $DRY_RUN_CMD ${pkgs.stow}/bin/stow \
          --dir="${dotfilesDir}" \
          --target="${config.home.homeDirectory}" \
          --no-folding \
          --restow \
          ${stowPackage}

        echo "hypr-local: restowed ${stowPackage}"
      fi
    '';
}
