{ config, lib, pkgs, ... }:

let
  # The manager pulls End-4's checkout into this repository and layers its
  # upstream package underneath the local Stow packages.
  dotfilesDir = "${config.home.homeDirectory}/.config/dotfiles";
  upstreamDotfilesDir = "${dotfilesDir}/hyprland-dotfiles";
  dotfilesManager = "${dotfilesDir}/stow-manager/.local/bin/dotfiles";
  pluginConfig = lib.concatMapStrings (
    plugin: ''
      hl.plugin("${plugin}/lib/lib${plugin.pname}.so")
    ''
  ) config.programs.illogical-impulse.hyprland.plugins;
in
{
  # The upstream module's implementation deletes and recopies ~/.config. Keep
  # the package, fonts, and QuickShell integration, but disable that ownership
  # boundary so Stow is the only file deployment mechanism.
  home.activation.copyIllogicalImpulseConfigs = lib.mkForce (
    config.lib.dag.entryAfter [ "writeBoundary" ] ''
      echo "illogical-flake: configuration copy disabled; using Stow layers"
    ''
  );

  home.activation.updateHyprlandDotfiles =
    config.lib.dag.entryAfter [ "copyIllogicalImpulseConfigs" ] ''
      if [ ! -x "${dotfilesManager}" ]; then
        echo "dotfiles: ${dotfilesManager} not found; skipping upstream sync" >&2
      elif [ -n "''${DRY_RUN_CMD:-}" ]; then
        PATH="${pkgs.git}/bin:${pkgs.stow}/bin:$PATH" "${dotfilesManager}" check
      elif [ -d "${upstreamDotfilesDir}" ] && [ -n "$(PATH="${pkgs.git}/bin:$PATH" git -C "${upstreamDotfilesDir}" status --porcelain 2>/dev/null)" ]; then
        echo "dotfiles: upstream checkout has local changes; skipping upstream sync" >&2
      else
        PATH="${pkgs.git}/bin:${pkgs.stow}/bin:$PATH" "${dotfilesManager}" upstream-update
      fi
    '';

  home.activation.writeHyprlandNixOverrides =
    config.lib.dag.entryAfter [ "updateHyprlandDotfiles" ] ''
      if [ -z "''${DRY_RUN_CMD:-}" ] && [ -d "$HOME/.config/hypr/custom" ]; then
        cat > "$HOME/.config/hypr/custom/env.lua" <<'LUAEOF'
-- Generated by Home Manager. Keep machine-specific Nix paths here; personal
-- Hyprland behavior belongs in the Stow-managed custom/*.lua files.
local home_dir = os.getenv("HOME") or ""
local user     = os.getenv("USER") or ""

hl.env("PATH",
  home_dir .. "/.nix-profile/bin" ..
  ":/etc/profiles/per-user/" .. user .. "/bin" ..
  ":" .. (os.getenv("PATH") or "/usr/local/bin:/usr/bin:/bin"))

hl.env("XDG_DATA_DIRS",
  home_dir .. "/.local/share" ..
  ":" .. home_dir .. "/.nix-profile/share" ..
  ":/etc/profiles/per-user/" .. user .. "/share" ..
  ":/run/current-system/sw/share" ..
  ":" .. home_dir .. "/.local/share/flatpak/exports/share" ..
  ":/var/lib/flatpak/exports/share" ..
  ":/usr/local/share:/usr/share")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
LUAEOF

        cat > "$HOME/.config/hypr/custom/general.lua" <<'LUAEOF'
-- Generated by Home Manager. Personal general settings belong in the
-- Stow-managed custom/general.lua file when the upstream layout supports it.
${pluginConfig}LUAEOF
        chmod u+rw "$HOME/.config/hypr/custom/env.lua" \
          "$HOME/.config/hypr/custom/general.lua"
        echo "dotfiles: wrote Nix-specific Hyprland overrides"
      fi
    '';
}
